### ISSUE TITLE
Alpine improvement (to get it working)

### ISSUE THREAD

**Issue by Takalele** [moonbuggy/docker-apt-cacher-ng#1]
Hi,

to get alpine working, it is necessary to adjust the VfilePatternEx and PfilePatternEx parameters; otherwise, the client will encounter a 403 error.

allow everything:
```
VfilePatternEx: .*
PfilePatternEx: .*
```
or more secure(tested with debian, ubuntu and alpine):
```
VfilePatternEx: (metalink\?repo=[0-9a-zA-Z-]+&arch=[0-9a-zA-Z_-]+|/\?release=[0-9]+&arch=|repodata/.*\.(xml|sqlite)\.(gz|bz2)|APKINDEX.tar.gz|filelists\.xml\.gz|filelists\.sqlite\.bz2|repomd\.xml|packages\.[a-zA-Z][a-zA-Z]\.gz)
PfilePatternEx: (/dists/.*/by-hash/.*|\.tgz|\.tar|\.xz|\.zip|\.jar|\.ver|\.bz2|\.rpm|\.apk)$
```

It would be great if the two could also be available as environment variables.

and thank you for your image!

BR
Takalele

**Comment by moonbuggy** [comment]
I had noticed some errors popping up, but have been too busy with other projects to look into it properly, so I keep concluding that apt-cacher-ng is a problem for another day. I've just been using [soulteary/apt-proxy](https://github.com/soulteary/apt-proxy) for Alpine instead. :)

Anyway,, I've made the file pigeonholing regexes configurable through ENV variables, and I've set your more secure recommendations as the defaults (commit: bc328bc6608909270b9a7f4783d040244ba52db7 - I fixed up a couple of other minor issues while I was in there, so it's not solely the regex stuff that changed.)

I'm getting 503's trying to pull _APKINDEX.tar.gz_, but I was getting those anyway,. So I can't really test sensibly, but there's no obvious negative impact I can see, so I've pushed the images.

Would you mind confirming for me that the changes work as expected for you?

**Comment by Takalele** [comment]
Hi @moonbuggy

yeah it works! thank you very much!

BR
Takalele
